name = input('Enter a name: ')
adjective = input('Enter an adjective: ')
noun = input('Enter a noun: ')
pronoun = input('Enter a pronoun: ')
title = input('Enter a title: ')
place = input('Enter a place: ')
verb = input('Enter a verb: ')
ending = input("Enter an ending word: ")

print(f"'{title}' by {name}, ")
print(f"{noun} by stone {pronoun} pile")
print(f"this {noun} of {pronoun} intention")
print(f"with the {noun}’s weight on {pronoun} back,")
print(f"{verb} and {adjective}")
print(f"across the slanting {noun}")
print(f"which {pronoun} love but cannot save")
print(f"from floods that are to come;")
print(f"can only {verb} down")
print(f"with this work of {pronoun} hands,")
print(f"these painfully {verb}")
print(f"{noun}, in the shape of nothing")
print(f"that has ever existed before.")
print(f"A pile of {noun}: an assertion")
print(f"that this piece of {place} matters")
print(f"for {adjective} and {adjective} reasons.")
print(f"A mark of resistance, a {ending}.")
